### ISSUE TITLE
Unexpected key 'HibernationOptions' found in params

### ISSUE THREAD

**Issue by lenawal** [aws/aws-sdk-js#2421]
When trying to launch an instance and specifying the Hibernation options parameter I get the following error:

> "errorMessage": "Unexpected key 'HibernationOptions' found in params",
>   "errorType": "UnexpectedParameter"

```
let ec2 = new AWS.EC2();
let params = {
        HibernationOptions: {
              Configured: true
        },
        ImageId: AMI_ID, 
        InstanceType: INSTANCE_TYPE,   
        MaxCount: 1, 
        MinCount: 1, 
        ...
};
ec2.runInstances(params, function(err, data) {
        if(err) return cb(err);
        console.log(data);
        return cb(null);
});
```

The documentation says that the parameter can be provided with the [runInstances](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#runInstances-property) function. Am I missing something?

**Comment by srchase** [comment]
@lenawal 

Does your instance meet the [EC2 Hibernation Prerequisites](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Hibernate.html#hibernating-prerequisites)?

**Comment by lenawal** [comment]
@srchase 
Yes, it does meet all the prerequisites. 
Also, I am able to launch an instance with hibernation enabled using the console, but when trying to launch an instance with the same configuration (the same encrypted ami and instance type c5.large) using the javascript sdk I get the error.

**Comment by srchase** [comment]
@lenawal 

Which version of the SDK are you running?

Hibernation was made available in the SDK on the EC2 StartInstances beginning in 2.366.0.  See [Changelog](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#23660).

Upgrading to a version of the SDK 2.366.0 or newer should resolve this issue.

**Comment by lenawal** [comment]
@srchase Sorry for the late response. This issue is still not resolved for me. I am using the latest version of the SDK. I am calling this code from a lambda function, so I assume the latest sdk version is beeing used. 
Any help is appreciated.

**Comment by srchase** [comment]
@lenawal 

Lambda is still using version 2.290.0.  Unfortunately, Lambda doesn't pull in the latest version automatically.

See this page: [Lambda Execution Environment and Available Libraries](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)

You'll need to bundle the SDK into your Lambda to use HibernationOptions.  Are you already doing that?  Or relying on the SDK that's included with Lambda?

**Comment by lenawal** [comment]
This resolved the issue, thank you!
